version: '3.9'
services:
  web:
    build: .
    command: sh -c "rm -f /rei_kc_stn/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    volumes:
      - .:/rei_kc_stn
    ports:
      - "80:3000"
    environment:
      RAILS_ENV: production
  css:
    build: .
    command: bundle exec rails dartsass:watch
    volumes:
      - .:/rei_kc_stn
    depends_on:
      - web
