default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: rei_kc_stn_pass
  pool: 5

development:
  <<: *default
  database: rei_kc_stn_development

test:
  <<: *default
  database: rei_kc_stn_test

production:
  <<: *default
  database: rei_kc_stn_production
  username: <%= ENV["REI_KC_STN_DATABASE_USER"] %>
  host: <%= ENV["REI_KC_STN_DATABASE_HOST"] %>
  password: <%= ENV["REI_KC_STN_DATABASE_PASSWORD"] %>
